name: Ruby

on: [push]

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Install dependencies
      run: bundle install --jobs 4

    - name: Run RSpec
      run: bundle exec rspec
