name: Ruby

on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
    name: Ruby ${{ matrix.ruby }} RSpec
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: 'Set RSpec exclude pattern for Ruby < 2.7'
      run: echo "::set-output name=value::**/*_gte_ruby_2_7_spec.rb"
      if: matrix.ruby == '2.5' || matrix.ruby == '2.6'
      id: rspec_exclude_pattern
    - run: bundle exec rspec --exclude-pattern=${{ steps.rspec_exclude_pattern.outputs.value }}
