name: Ruby

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.5.x'
          - '2.6.x'

    name: Ruby ${{ matrix.ruby }} RSpec

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install latest bundler
      run: gem install bundler

    - name: Install operatic dependencies
      run: bundle install --jobs 4

    - name: Run RSpec
      run: bundle exec rspec
